apiVersion: batch/v1
kind: Job
metadata:
  name: printenv
spec:
  parallelism: 1
  completions: 8
  template:
    metadata:
      name: printmessage
    spec:
      containers:
      - name: printmessage
        image: busybox
        command: ["/bin/sh", "-c", "env"]
      restartPolicy: Never 
