apiVersion: v1
kind: ReplicationController
metadata:
  name: emptyrc-2
spec:
  replicas: 1  
  selector:    
    name: emptyrc
  template:    
    metadata:
      labels:  
        name: emptyrc 
    spec:
      containers:
      - image: openshift/hello-openshift
        name: helloworld
        ports:
        - containerPort: 8080
          protocol: TCP
      restartPolicy: Always



