apiVersion: batch/v1
kind: Job
metadata:
  name: printmessage
spec:
  parallelism: 4
  completions: 8
  template:
    metadata:
      name: printmessage
    spec:
      containers:
      - name: printmessage
        image: busybox
        command: ["sh", "-c", "echo 'Hello from job'; sleep 10; echo 'Goodbye now'"]
      restartPolicy: Never 
